### ISSUE TITLE
Division by zero error when being chased closely by a mob

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [MellowJay/tcod-game#1]
![image](https://user-images.githubusercontent.com/21359162/47445737-52f1b680-d7c2-11e8-9ace-a9d4f665a08e.png)

Seems like when there is 0 distance (troll on top of me?) The gaem crashes

I was moving downwards and being chased when the game crashed.

**Comment by MellowJay** [comment]
Hey, I fixed the bug! I tested the game on my end and everything seemed fine. Please play around with the game on your end and post if you encounter the bug again.

**Comment by EdvardasDlugauskas** [comment]
Seems to be resolved

**Comment by EdvardasDlugauskas** [comment]
Wait a second...

![image](https://user-images.githubusercontent.com/21359162/47609694-54361400-da4c-11e8-8e9a-d2442c1cee2c.png)

**Comment by EdvardasDlugauskas** [comment]
Fixed in #4
